CUDA_VISIBLE_DEVICES=1,2,3 mpirun -np 3 python finetune_sdm_INIT.py \
--cf /home/cvlab10/project/disco-i2i_GAN/config/ref_attn_clip_combine_controlnet/config_INIT_multi.py \
--eval_before_train True \
--do_train --root_dir /media/dataset/run_test_hw/ \
--log_dir Init/seg_edge_depth_resume \
--local_train_batch_size 24 \
--local_eval_batch_size 24 \
--epochs 500 --deepspeed \
--eval_step 1000 --save_step 1000 \
--gradient_accumulate_steps 1 \
--learning_rate 2e-4 --fix_dist_seed --loss_target "noise" \
--unet_unfreeze_type "all" \
--refer_sdvae \
--ref_null_caption False \
--combine_clip_local --combine_use_mask \
--conds "masks" \
--max_eval_samples 100 --node_split_sampler 0 \
--pretrained_model /media/dataset/run_test_hw/Init/seg_edge_depth/4999.pth